name: Release Pipeline

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run full validation
        run: |
          npm run validate
          npm run test:coverage
          node scripts/validate-manifest.js
          
      - name: Create release package
        run: |
          mkdir -p dist
          cp -r public/* dist/
          cp README.md dist/
          cp package.json dist/
          zip -r mini-translate-extension.zip dist
      
      - name: Create or update Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NOTES_FILE=release_notes.md
          cat > $NOTES_FILE << 'EOF'
          ## 🚀 Mini Translate Extension Release
          
          ### ✅ Quality Assurance
          - All tests passed (46/46)
          - ESLint static analysis passed (warnings non-blocking)
          - Manifest validation successful
          
          ### 📦 Installation
          1. Download the extension package
          2. Open Chrome and go to `chrome://extensions/`
          3. Enable "Developer mode"
          4. Click "Load unpacked" and select the extension folder
          
          ### 🔧 Features
          - Right-click context menu for vocabulary management (S1)
          - Page translation toggle (S1)
          - Local storage with 500-item limit (S2)
          - Translation service abstraction with multiple models (S3)
          - Chrome Manifest V3 compliant
          
          ### 📋 Changelog
          - Story S1: Context menu and page translation
          - Story S2: Vocabulary storage and management
          - Story S3: Translation service abstraction and tests
          - CI/CD pipeline integration
          EOF
          
          TAG="${{ github.ref_name }}"
          if ! gh release view "$TAG" >/dev/null 2>&1; then
            gh release create "$TAG" --title "Release $TAG" --notes-file "$NOTES_FILE"
          else
            gh release edit "$TAG" --notes-file "$NOTES_FILE"
          fi
          gh release upload "$TAG" mini-translate-extension.zip --clobber
